### ISSUE TITLE
Dimensional reduction by non classical approaches

### ISSUE THREAD

**Issue by abunickabhi** [syamkakarla98/Dimensionality-reduction-and-classification-on-Hyperspectral-Images-Using-Python#1]
Why not use Autoencoders for dim reduction rather than standard statistical one layer technique.
Since NN are the state of the art algorithmic approach.

**Comment by syamkakarla98** [comment]
Hello Abhijeet,
I’m looking into it. It was my mini project. That’s why I implanted in a basic way.
Looking forward,
You can catch me on linkedIn, Here is the link:
https://www.linkedin.com/in/syam-kakarla-7b3833148/?originalSubdomain=in

Sent from Mail for Windows 10

From: Abhijeet Go-kar
Sent: 22 March 2019 17:21
To: syamkakarla98/Dimensionality-reduction-and-classification-on-Hyperspectral-Images-Using-Python
Cc: Subscribed
Subject: [syamkakarla98/Dimensionality-reduction-and-classification-on-Hyperspectral-Images-Using-Python]Dimensional reduction by non classical approaches (#1)

Why not use Autoencoders for dim reduction rather than standard statistical one layer technique.
Since NN are the state of the art algorithmic approach.
